Fix OSError: [Errno 5] Input/output error
OSError: [Errno 5] Input/output error issued when GET study/title is called without an open session on the VM.
Removed some print() statements left only for debugging